const enTranslations = {
  translation: {
    common: {
      title: 'forghan',
      sura: 'surah',
      juz: 'juz',
      bookmark: 'bookmark',
      page: 'page',
      hizb: 'hizb',
      vers: 'ayah',
      words: 'words',
      letters: 'letters',
      order: 'order',
      makki: 'makki',
      readOnline: 'read online',
      more: 'more',
      medin: 'medin',
      translator: 'Translators',
      delete: 'Delete',
      checkNet: 'Check your connection',
      offline: 'You are offline!',
      recommended: 'Recommended for you',
    },
    offlineTips: {
      offlineTips:
        'but can download your favorite reciters or listen online by activating the streaming. it is free and unlimited.',
      loading: 'loading...',
      selectReciter: 'Select Reciter',
      close: 'Close',
      carMode: 'Car Mode',
      repeat: 'Repeat',
      repeatEachVerse: 'Repeat each verse',
      repeatAll: 'Repeat all of them',
      cancel: 'Cancel',
      ok: 'OK',
      repetitionSuccess: 'Repetition Values Seated',
      seatedSuccess: '{label} Seated',
    },
    setting: {
      jump: 'Jump',
      setting: 'Setting',
      general: 'General',
      recitation: 'Recitation',
      display: 'Display',
      translation: 'Translation',
      enableTranslationTip: 'Show translation below Ayahs',
      enableTranslation: 'Enable Translation',
      translators: 'Translators',
      defaultMode: 'Default mode',
      language: 'Language',
      appearance: 'Appearance',
      tajwid: 'Tajwid',
      streamQuality: 'Stream quality',
      recitationSpeed: 'Recitation speed',
      download: 'Download',
      reciters: 'Reciters',
      streaming: 'Streaming',
      streamingSub: 'Stream audio instead of downloading',
    },
    surah: {
      share: 'Share',
      copy: 'Copy',
      report: 'Report',
      bookmark: 'Bookmark',
      link: 'Get link',
    },
    juz: {
      hizb: 'Hizb',
      rubElHizb: 'Rub el Hizb',
      halfElHizb: 'Half el Hizb',
      threeRubHizb: 'Three rub el Hizb',
    },
    language: {
      arabic: 'Arabic (العربية)',
      english: 'English (US)',
      persian: 'Persian (فارسی)',
    },
    recitation: {
      offline: 'The recitations list needs to be online',
    },
    translator: {
      moreTranslation: 'More Translations',
      setAsDefaultSuccess: 'Translation Seated as default',
      offline: 'The translator list needs to be online',
      setPriority: 'Set Priority',
      setAsDefault: 'Set as default',
      viewAsBook: 'View as book',
      downloadTitle: 'download new translation',
      downloadSubtitle:
        'please wait until download finish, don\'t close the app',
      readingTitle: 'reading new translation',
      readingSubtitle: 'please wait until reding finish, don\'t close the app',
      maxTranslations: 'maximum selected translation is {val}',
    },
    deleteFileAlert: {
      title: 'Are You Sure?',
      subTitle: 'after deletion file is not available offline',
      ok: 'OK',
      cancel: 'Cancel',
    },
    tajwidRules: {
      title: 'Tajwid rules',
      subTitle: 'Enable or disable all rules',
      hamzatUlWasl: 'Hamzat ul Wasl',
      silent: 'Silent',
      lamShamiyyah: 'Lam Shamsiyyah',
      lamShamsiyah: 'laam Shamsiyah	',
      maddaNormal: 'Madda Normal',
      maddaNecessary: 'Madda Necesssary	',
      maddaPermissible: 'Madda Permissible',
      qalaqah: 'Qalaqah',
      ikhafaShafawi: 'Ikhafa Shafawi	',
      maddaObligatory: 'Madda Obligatory',
      ikhafa: 'Ikhafa',
      idghamShafawi: 'Idgham Shafawi',
      iglab: 'Iqlab',
      idhamWithGhunnah: 'Idgham With Ghunnah',
      idghamWithoutGhunnah: 'Idgham Without Ghunnah',
      idghamMutajanisayn: 'Idgham Mutajanisayn',
      idghamMutagaribayn: 'Idgham Mutaqaribayn',
      ghunnah: 'Ghunnah',
    },
    appearance: {
      quranText: 'Quran Text',
      fonts: 'Fonts',
      fontFamily: 'Font Family',
      fontSize: 'Font Size',
      fontColor: 'Font Color',
      paragraph: 'Paragraph',
      alignment: 'Alignment',
      letterSpacing: 'Letter spacing',
      lineHeight: 'Line Height',
    },
  },
};
export default enTranslations;
